project:
  type: website
  output-dir: ../_site/en
  resources:
    - nivel/superior/sisma/prat/contr.pdf
    - nivel/superior/sisma/prat/carb.pdf
    - nivel/superior/sisma/prat/carb_lip.pdf
    - nivel/superior/sisma/prat/a_nucl.pdf
#    - livrosVivos/Tutorial/_book/**
    - r/_book/**
    - biqTxT/_book/**
    # - nivel/superior/jsplotly/sbbq/vdw3D.html
    # - nivel/superior/jsplotly/sbbq/buffer_slider.html
    # - nivel/superior/jsplotly/sbbq/cargaPept_slider.html
    # - nivel/superior/jsplotly/sbbq/gibbs.html
    # - nivel/superior/jsplotly/sbbq/nyquist2.html
    # - nivel/superior/jsplotly/sbbq/3d.html

#NÃO renderizar os .qmd do livro dentro do site
render:
  - "!"                         # mantém seu padrão atual
  - "!livrosVivos/Tutorial/**"
  - "!r/_book/**"

website:
  page-navigation: true
  back-to-top-navigation: true
  image: unifal-logo.png
  reader-mode: true
  google-analytics: "G-S1L73VGCG5"
  title: ""
  favicon: avatar.png

  sidebar:
    collapse-level: 1    # só nível 1 aberto; subtópicos (nível 2+) fechados
    # collapse-level: 0  # tudo fechado (inclusive o 1º nível)
    contents:
      - section: "JSPlotly: Interactive objects & AI"
        contents:
          - text: "JSPlotly"
            href: nivel/superior/jsplotly/jsplotly_geral_en.qmd
          - text: "GSPlotly - AI code generator"
            href: nivel/superior/jsplotly/gsplotly_en.qmd
          - text: "Biophysical chemistry"
            href: nivel/superior/jsplotly/jsptl_bioq_en.qmd
          - text: "School"
            href: nivel/basico/jsplotly/jsplotly_bas_en.qmd
          
            
      - section: "Jmol - 3D molecules"
        contents:
          - text: "Biochemistry"
            href: nivel/superior/jmol/index_jmol_en.qmd
          - text: "School"
            href: nivel/basico/Curso/index_jmol_bas_en.qmd
          - text: "Molecule Garden"
            href: nivel/basico/Jardim/index_Jardim_en.qmd

      - section: "R - Maths and charts"
        contents:
          - text: "Biophysical chemistry"
            href: nivel/superior/r/_book/index_en.html
          - text: "scriptRplot: elegant graphics"
            href: nivel/superior/ScriptRplot/scriptrplot_en.qmd
          - text: "School"
            href: nivel/basico/Curso/index_r_bas_en.qmd
          - text: "Interactivity at School"
            href:  nivel/basico/R/index_OIER_en.qmd


      - section: "Sisma - dynamic flows"
        contents:
          - text: "Biochemistry"
            href: nivel/superior/sisma/index_sisma_en.qmd
          - text: "School"
            href: nivel/basico/sisma/index_sisma_bas_en.qmd


  navbar:
    logo: logo-unifal.png
    search: true
    tools:
      - icon: true
        html: |
          <a href="https://www.unifal-mg.edu.br" target="_blank">
            <img src="../images/logo-unifal.png" alt="UNIFAL" style="height:40px; vertical-align:middle; margin-right:15px;"></a>
      - icon: true
        html: |
          <a href="https://www.capes.gov.br" target="_blank">
            <img src="../images/logo-capes.png" alt="CAPES" style   ="height:40px; vertical-align:middle; margin-left:15px;"></a>

    left:
    
      - text: "About"
        id: sup-menu
        href: index.html
      - text: "Reproducible Teaching"
        id: bas-menu
        href: erre_en.qmd

      - text: "Cheatsheets"
        id: sup-menu
        menu: 
          - text: "Plotly"
            href: cheatsheet/plotly.pdf
          - text: "Jmol"
            href: cheatsheet/jmol_cheat.pt.pdf
          - text: "R"
            href: cheatsheet/r_cheat.pt.pdf
          

      - text: "Works"
        href: producao_en.qmd

      - text: "Contact"
        href: contato_en.qmd
         
    right:
      - text: "PT"
        href: ../pt/index.html


format:
  html:
    theme: 
      light: flatly
    css: 
      - styles.css
#      - styles.pastel.css   # <- este vem por último para sobrepor
    code-overflow: wrap

execute:
  cache: true
  message: false
  warning: false
