project:
  type: website
  output-dir: ../_site/pt
  resources:
    - nivel/superior/sisma/prat/contr.pdf
    - nivel/superior/sisma/prat/carb.pdf
    - nivel/superior/sisma/prat/carb_lip.pdf
    - nivel/superior/sisma/prat/a_nucl.pdf
    
    # - livrosVivos/Tutorial/_book/**
    # - nivel/superior/jsplotly/sbbq/vdw3D.html
    # - nivel/superior/jsplotly/sbbq/buffer_slider.html
    # - nivel/superior/jsplotly/sbbq/cargaPept_slider.html
    # - nivel/superior/jsplotly/sbbq/gibbs.html
    # - nivel/superior/jsplotly/sbbq/nyquist2.html
    # - nivel/superior/jsplotly/sbbq/3d.html
    
#COPIAR o book já renderizado para o site
resources:
  - livrosVivos/Tutorial/_book/**
  - r/_book/**
  - biqTxT/_book/**

#NÃO renderizar os .qmd do livro dentro do site
render:
  - "!"                         # mantém seu padrão atual
  - "!livrosVivos/Tutorial/**"
  - "!r/_book/**"

    

website:
  page-navigation: true
  back-to-top-navigation: true
  image: unifal-logo.png
  reader-mode: true
  google-analytics: "G-S1L73VGCG5"
  title: ""
  favicon: avatar.png

  sidebar:
    collapse-level: 1    # só nível 1 aberto; subtópicos (nível 2+) fechados
    # collapse-level: 0  # tudo fechado (inclusive o 1º nível)
    contents:
      - section: "JSPlotly: objetos interativos & IA"
        contents:
          - text: "JSPlotly"
            href: nivel/superior/jsplotly/jsplotly_geral.qmd
          - text: "GSPlotly - gerador de códigos por IA"
            href: nivel/superior/jsplotly/gsplotly.qmd
          - text: "Biofísico-química"
            href: nivel/superior/jsplotly/jsplt_bioq.qmd
          - text: "Escola"
            href: nivel/basico/jsplotly/jsplotly_bas.qmd
          
            
      - section: "Jmol - Moléculas em 3D"
        contents:
          - text: "Bioquímica"
            href: nivel/superior/jmol/index_jmol.qmd
          - text: "Escola"
            href: nivel/basico/Curso/index_jmol_bas.qmd
          - text: "Jardim de Moléculas"
            href: nivel/basico/Jardim/index_Jardim.qmd

      - section: "R - Cálculos e gráficos"
        contents:
          - text: "Biofísico-química"
            href: nivel/superior/r/_book/index.html
          - text: "scriptRplot: gráficos elegantes"
            href: nivel/superior/ScriptRplot/scriptrplot.qmd
          - text: "Escola"
            href: nivel/basico/Curso/index_r_bas.qmd
          - text: "Objetos interativos na Escola"
            href:  nivel/basico/R/index_OIER.qmd


      - section: "Sisma - fluxos dinâmicos"
        contents:
          - text: "Bioquímica"
            href: nivel/superior/sisma/index_sisma.qmd
          - text: "Escola"
            href: nivel/basico/sisma/index_sisma_bas.qmd
            
      - section: "Livro-texto de Bioquímica"
        contents:
          - text: "Bioquímica de Gente, de Bicho e de Planta"
            href: nivel/superior/biqTxT/_book/index.html


  navbar:
    search: true
    logo: logo-unifal.png

    left:
      #
      # - text: ""
      #   href: images/logo-unifal.png

      - text: "Sobre"
        id: sup-menu
        href: index.html
      - text: "Ensino Reprodutível"
        id: bas-menu
        href: erre.qmd
        
      - text: "Folhas de dicas"
        id: sup-menu
        menu: 
          - text: "Plotly"
            href: cheatsheet/plotly.pdf
          - text: "Jmol"
            href: cheatsheet/jmol_cheat.pt2.pdf
          - text: "R"
            href: cheatsheet/r_cheat.pt.pdf
          

      - text: "Trabalhos"
        href: producao.qmd

      - text: "Contato"
        href: contato.qmd
         
    right:
    
      - text: "EN"
        href: ../en/index.html


format:
  html:
    theme: 
      light: flatly
    css: 
      - styles.css
 #     - styles.pastel.css   # <- este vem por último para sobrepor
    code-overflow: wrap

execute:
  cache: true
  message: false
  warning: false
